name: CI/CD Pipeline

# Trigger the workflow on a push to the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Step 6: Copy docker-compose.yml
      - name: Deploy file to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USERNAME }}/pf_microservice"
      # Step 7: Deploy to Oracle VM via SSH
      - name: Add docker username to env
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}